#cloud-config

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/e2064a6a7f383ad617949d898563d3cb
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380
# Configure Update:
  update:
    reboot-strategy: etcd-lock
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
# Stop Update
    - name: update-engine.service
      runtime: false
#Configure weave
    - name: 10-weave.network
      runtime: false
      content: |
        [Match]
        Type=bridge
        Name=weave*

        [Network]

    - name: install-weave.service
      command: start
      enable: true
      content: |
        [Unit]
        After=network-online.target
        After=docker.service
        Description=Install Weave
        Documentation=http://zettio.github.io/weave/
        Requires=network-online.target
        Requires=docker.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/bin/mkdir -p /opt/bin/
        ExecStartPre=/usr/bin/curl \
          --silent \
          --location \
          https://github.com/weaveworks/weave/releases/download/latest_release/weave \
          --output /opt/bin/weave
        ExecStartPre=/usr/bin/chmod +x /opt/bin/weave
        ExecStartPre=/usr/bin/docker pull zettio/weave:latest
        ExecStartPre=/usr/bin/docker pull zettio/weavetools:latest
        ExecStartPre=/usr/bin/docker pull zettio/weavedns:latest
        ExecStartPre=/usr/bin/docker pull weaveworks/weaveexec:latest
        ExecStart=/bin/echo Weave Installed
    - name: swapon.service
      command: start
      enable: true
      content: |
        [Unit] 
        Description=Turn on swap
        
        [Service]
        Type=oneshot
        Environment="SWAPFILE=/mnt/resource/4GiB.swap"
        RemainAfterExit=true
        ExecStartPre=/usr/bin/touch ${SWAPFILE}
        ExecStartPre=/usr/bin/fallocate -l 4096m ${SWAPFILE}
        ExecStartPre=/usr/bin/chmod 600 ${SWAPFILE}
        ExecStartPre=/usr/sbin/mkswap ${SWAPFILE}
        ExecStartPre=/usr/sbin/losetup -f ${SWAPFILE}
        ExecStart=/usr/bin/sh -c "/sbin/swapon $(/usr/sbin/losetup -j ${SWAPFILE} | /usr/bin/cut -d : -f 1)"
        ExecStop=/usr/bin/sh -c "/sbin/swapoff $(/usr/sbin/losetup -j ${SWAPFILE} | /usr/bin/cut -d : -f 1)"
        ExecStopPost=/usr/bin/sh -c "/usr/sbin/losetup -d $(/usr/sbin/losetup -j ${SWAPFILE} | /usr/bin/cut -d : -f 1)"

        [Install]
        WantedBy=multi-user.target

        [X-Fleet]
        Global=true 

